# genes_map.py
GENE_MECH = {
    "TP53": "Tumor Suppressor",
    "RB1": "Tumor Suppressor",
    "PTEN": "Tumor Suppressor",
    "BRCA1": "Tumor Suppressor",
    "BRCA2": "Tumor Suppressor",
    "APC": "Tumor Suppressor",
    "NF1": "Tumor Suppressor",
    "NF2": "Tumor Suppressor",
    "VHL": "Tumor Suppressor",
    "CDKN2A": "Tumor Suppressor",
    "SMAD4": "Tumor Suppressor",
    "ARID1A": "Tumor Suppressor",
    "ATM": "Tumor Suppressor",
    "ATR": "Tumor Suppressor",
    "CHEK2": "Tumor Suppressor",
    "FANCA": "Tumor Suppressor",
    "FANCC": "Tumor Suppressor",
    "FANCD2": "Tumor Suppressor",
    "MLH1": "Tumor Suppressor",
    "MSH2": "Tumor Suppressor",
    "MSH6": "Tumor Suppressor",
    "PMS2": "Tumor Suppressor",
    "SMARCB1": "Tumor Suppressor",
    "WT1": "Tumor Suppressor",
    "TSC1": "Tumor Suppressor",
    "TSC2": "Tumor Suppressor",
    "DCC": "Tumor Suppressor",
    "CDH1": "Tumor Suppressor",
    "MEN1": "Tumor Suppressor",
    "SUFU": "Tumor Suppressor",
    "PTCH1": "Tumor Suppressor",
    "KEAP1": "Tumor Suppressor",
    "STK11": "Tumor Suppressor",
    "FBXW7": "Tumor Suppressor",
    "NFIB": "Tumor Suppressor",
    "SMARCA4": "Tumor Suppressor",
    "NPM1": "Tumor Suppressor",

    "EGFR": "Oncogene",
    "ERBB2": "Oncogene",
    "ERBB3": "Oncogene",
    "ERBB4": "Oncogene",
    "ALK": "Oncogene",
    "ROS1": "Oncogene",
    "RET": "Oncogene",
    "MET": "Oncogene",
    "BRAF": "Oncogene",
    "KRAS": "Oncogene",
    "HRAS": "Oncogene",
    "NRAS": "Oncogene",
    "PIK3CA": "Oncogene",
    "PIK3CB": "Oncogene",
    "PIK3CD": "Oncogene",
    "AKT1": "Oncogene",
    "AKT2": "Oncogene",
    "AKT3": "Oncogene",
    "MYC": "Oncogene",
    "MYCN": "Oncogene",
    "MYCL": "Oncogene",
    "CCND1": "Oncogene",
    "CCND2": "Oncogene",
    "CCND3": "Oncogene",
    "MDM2": "Oncogene",
    "MDM4": "Oncogene",
    "FGFR1": "Oncogene",
    "FGFR2": "Oncogene",
    "FGFR3": "Oncogene",
    "FGFR4": "Oncogene",
    "KIT": "Oncogene",
    "PDGFRA": "Oncogene",
    "PDGFRB": "Oncogene",
    "JAK1": "Oncogene",
    "JAK2": "Oncogene",
    "JAK3": "Oncogene",
    "TYK2": "Oncogene",
    "FLT3": "Oncogene",
    "FLT1": "Oncogene",
    "FLT4": "Oncogene",
    "NTRK1": "Oncogene",
    "NTRK2": "Oncogene",
    "NTRK3": "Oncogene",
    "GNAQ": "Oncogene",
    "GNA11": "Oncogene",
    "IDH1": "Oncogene",
    "IDH2": "Oncogene",
    "NOTCH1": "Oncogene",
    "NOTCH2": "Oncogene",
    "NOTCH3": "Oncogene",
    "SMO": "Oncogene",
    "SHH": "Oncogene",          # Replaced pathway name with gene symbol
    "MAP2K1": "Oncogene",
    "MAP2K2": "Oncogene",
    "ABL1": "Oncogene",
    "ABL2": "Oncogene",
    "SRC": "Oncogene",
    "YES1": "Oncogene",
    "FYN": "Oncogene",
    "LCK": "Oncogene",
    "BLK": "Oncogene",
    "FER": "Oncogene"
}
